name = "FractalAnimation"
uuid = "6118da02-c7f1-44e0-8933-0c8b5cc44c9b"
authors = ["ErrolSeders <errolbucy@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
